### ISSUE TITLE
How to obtain the filtered dataset for APE?

### ISSUE THREAD

**Issue by allanj** [qinzhuowu/NumS2T#4]
I ran the `run_seq2tree_APE.py` and get the following information.

which is inconsistent with the number in the paper `166,270, 4,157, and 4,159`

```bash
5000
2
112
4886
Transfer numbers...
count_empty
59
data_set_size is 193743, num of exp>60  is 1070,about 0.0055
data_set_size is 193743, num of problem>150  is 1014,about 0.0052
******
```

```bash
Transfer numbers...
count_empty
1
data_set_size is 4840, num of exp>60  is 24,about 0.0050
data_set_size is 4840, num of problem>150  is 21,about 0.0043
Indexing words...
keep_words 2722 / 3837 = 0.7094
```

I also got an error saying
```bash
hownet//hownet_dict_all file not found
```
after setting `USE_KAS2T_encoder=False`

I got the following error:
```bash
Traceback (most recent call last):
  File "/Users/allanjie/projects/NumS2T/run_seq2tree_APE.py", line 66, in <module>
    input_lang,output_lang,train_pairs,test_pairs,matrix,category_vocab,hownet_dict_vocab=prepare_data(pairs, pairs_from_test,
  File "/Users/allanjie/projects/NumS2T/pre_data.py", line 813, in prepare_data
    matrix, size, in_vocab_num=load_dense_drop_repeat(input_lang,"..//..//Solve_1101//data//sgns.baidubaike.bigram-char")
  File "/Users/allanjie/projects/NumS2T/pre_data.py", line 743, in load_dense_drop_repeat
    with codecs.open(path, "r", "utf-8") as f:
  File "/Users/allanjie/anaconda3/envs/general/lib/python3.9/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '..//..//Solve_1101//data//sgns.baidubaike.bigram-char'
```

**Comment by allanj** [comment]
If possible, can you release the filtered-version dataset?

**Comment by qinzhuowu** [comment]
hownet//hownet_dict_all file is under the main branch in the hownet fold。hownet 在上一层有一个文件夹，我就没有再复制到NumS2T_APE_0521底下。Solve_1101//data//sgns.baidubaike.bigram-char是百度百科的词向量文件，我自己的目录，你要改成你的目录。由于有1.2个G,实在难以传到github上去。我是从这里下的，https://github.com/Embedding/Chinese-Word-Vectors。网上也有别的下载链接。

193743这个是不是没筛，这应该是只过了最大长度，表达式是不是可以求解，求解后能不能生成答案这一步筛选。接下来有一个函数是检验表达式里的数值是不是都出现在问题里的，166,270, 4,157, and 4,159 是经过这个过滤过程后的题量。


The filter operation is processed in the pre_data.py.
We load the data directly from the original dataset file and filter them during the preprocessing stage, after several function like "load_data","pre_data", the data we send to the model are already being filtered. We didn't save them sepereately.
The filter operation are mostly check by whether the number in the expression are also in the problem.
这个数据集它没有很好的清洗，有的解是多个表达式只提供给了我们一个最长的表达式做ground truth，这样就把一些中间表达式省略了。你会发现有的时候表达式里面出现的数字是需要计算出来的，但问题原文里面没有直接提供，这样就很难让模型直接复制这些数字。我们主要把这些情况过滤掉了。
我们的过滤过程都是写在了函数里自动过滤，没有另外把过滤出来的问题再组建一个数据集。
如果需要过滤后的数据集，在for n_epoch in epoches:前面把train_data里面的问题额外保持下来也可以,但我们觉得从原始数据加载更方便之后的研究人员进行下一步研究。
-----原始邮件-----
发件人:"Allan Jie" ***@***.***>
发送时间:2021-11-10 11:44:00 (星期三)
收件人: qinzhuowu/NumS2T ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [qinzhuowu/NumS2T] How to obtain the filtered dataset for APE? (Issue #4)



If possible, can you release the filtered-version dataset?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SCUTykLin** [comment]
到底是在哪里过滤了，for epoch in range(start_epoch,n_epochs):前面train都还是19w啊

**Comment by qinzhuowu** [comment]
run_seq2tree里面第95-107行，判断表达式里面有没有UNK，如果有的话将这个数据过滤掉。


    UNK= output_lang.word2index["UNK"]
    temp_pairs = []
    i=0
    for p in train_pairs:
        if UNK not in p[2]:
            temp_pairs.append(p)
        else:
            i+=1
            if i<5:
                print( " ".join(indexes_to_sentence(input_lang,p[0])))
                print( " ".join(indexes_to_sentence(output_lang,p[2])))

-----原始邮件-----
发件人:GreenArrow2017 ***@***.***>
发送时间:2021-12-07 16:10:04 (星期二)
收件人: qinzhuowu/NumS2T ***@***.***>
抄送: qinzhuowu ***@***.***>, Comment ***@***.***>
主题: Re: [qinzhuowu/NumS2T] How to obtain the filtered dataset for APE? (Issue #4)



到底是在哪里过滤了，for epoch in range(start_epoch,n_epochs):前面train都还是19w啊

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SCUTykLin** [comment]
> run_seq2tree里面第95-107行，判断表达式里面有没有UNK，如果有的话将这个数据过滤掉。 UNK= output_lang.word2index["UNK"] temp_pairs = [] i=0 for p in train_pairs: if UNK not in p[2]: temp_pairs.append(p) else: i+=1 if i<5: print( " ".join(indexes_to_sentence(input_lang,p[0]))) print( " ".join(indexes_to_sentence(output_lang,p[2])))
> […](#)
> -----原始邮件----- 发件人:GreenArrow2017 ***@***.***> 发送时间:2021-12-07 16:10:04 (星期二) 收件人: qinzhuowu/NumS2T ***@***.***> 抄送: qinzhuowu ***@***.***>, Comment ***@***.***> 主题: Re: [qinzhuowu/NumS2T] How to obtain the filtered dataset for APE? (Issue #4) 到底是在哪里过滤了，for epoch in range(start_epoch,n_epochs):前面train都还是19w啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

谢谢，明白
